# pyproject.toml

[build-system]
requires      = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "MultiVeloVAE"
version = "0.1.0"
authors = [
    {name = "Chen Li"},
    {name = "Yichen Gu"},
]
maintainers = [
    {name = "Chen Li", email = "chlseven@umich.edu"},
]
description = "Velocity inference from multi-lineage, multi-omic, and multi-sample single-cell data"
readme = "README.md"
license = {text = "BSD-3"}
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Natural Language :: English",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
keywords = [
    "bioinformatics",
    "single-cell",
    "multi-omic",
    "batch correction",
    "trajectory inference",
    "RNA velocity",
]
dependencies = [
    "anndata>=0.8.0",
    "hnswlib>=0.6.2",
    "igraph>=0.10.4",
    "ipywidgets",
    "leidenalg",
    "loess>=2.1.2",
    "matplotlib>=3.3.0",
    "multivelo>=0.1.2",
    "numpy>=1.17",
    "pandas>=0.23".
    "plotnine",
    "scanpy>=1.5",
    "scikit-learn>=0.20",
    "scikit-misc",
    "scipy>=1.13.0",
    "scvelo>=0.2.3",
    "seaborn>=0.10.0",
    "torch>=1.8.0",
    "tqdm",
    "umap-learn",
]

[project.optional-dependencies]
dev = [
    "pytest>=6.0",
    "black",
    "flake8",
]

[project.urls]
Homepage = "https://github.com/welch-lab/MultiVeloVAE"

[tool.black]
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.nox
  | \.tox
  | \.venv
  | \.ipynb_checkpoints
  | _build
  | buck-out
  | build
  | dist
)/
'''